public enum C_origen {
    ANDALUCIA, BUGALAGRANDE, EL_CERRITO, GINEBRA, GUACARI, BUGA, RIOFRIO, TRUJILLO, CALIMA, DARIEN, RESTREPO, SAN_PEDRO,
    TULUA, YOTOCO, EL_AGUILA, ALCALA, ANSERMANUEVO, ARGELIA, EL_CAIRO, LA_UNION, LA_VICTORIA, ULLOA, BOLIVAR, CARTAGO,
    EL_DOVIO, OBANDO, ROLDANILLO, TORO, VERSALLES, ZARZAL, BUENAVENTURA, CAICEDONIA, SEVILLA, CALI, CANDELARIA, PALMIRA,
    DAGUA, FLORIDA, JAMUNDI, LA_CUMBRE, PRADERA, VIJES, YUMBO
}
