public enum Partido_p {
    LA_FUERZA_DE_LA_PAZ,MOVIMIENTO_FUERZA_CIUDADANA,NUEVA_FUERZA_DEMOCRATICA,
    CREEMOS,
    GENTE_EN_MOVIMIENTO,
    EL_TRABAJO_DE_COLOMBIA,
    PARTIDO_DEMOCRATA_COLOMBIANO,PARTIDO_LIBERAL_COLOMBIANO,PARTIDO_CONSERVADOR_COLOMBIANO,
    PARTIDO_CAMBIO_RADICAL,PARTIDO_ALIANZA_VERDE,AICO,
    PARTIDO_ALIANZA_SOCIAL_INDEPENDIENTE_ASI,MIRA,PARTIDO_DE_LA_U,
    PARTIDO_POLO_DEMOCRATICO_ALTERNATIVO,PARTIDO_UNION_PATRIOTICA_UP,PARTIDO_CENTRODEMOCRATICO,MAIS
}
